package jp.co.toukei.log.lib.util

import kotlin.math.max

class IdGenerator<T>(initLength: Int) {

    private val array = ArrayList<T>(initLength)
    private val hash = HashMap<T, Int>(max(initLength * 2, initLength))

    /**
     * returns same id on same value (equals).
     */
    fun genId(value: T): Int {
        return hash[value] ?: array.size.also {
            array.add(value)
            hash[value] = it
        }
    }

    /**
     * don't abuse.
     * @param id must be generated by [genId]
     */
    fun getValue(id: Int): T {
        return array[id]
    }
}
