//
//  Resources.swift
//  TrustarApp
//
//  Created by DionSoftware on 2022/01/18.
//

import Foundation
import UIKit

class Resources
{
    static let HOST_URL = "https://www.trustar-system.com"
    static let API_URL = "/trustar-api-dev/"
    static let MESSAGE_API_URL = "/message-api_dev/"
    static let API_KEY = "d60a2885f8bab7a3f8df635cc72a6ebf"
//    static let MESSAGE_API_KEY = "D60A2885F8BAB7A3F8DF635CC72A6EBF"
    static let MESSAGE_API_KEY = "123"
    static let APP_BUNDLE_URL = "https://itunes.apple.com/jp/lookup?bundleId={0}"
    static let APP_ID_URL = "itms-apps://itunes.apple.com/app/apple-store/{0}?mt=8"
    
    static let strEmpty = ""
    static let zeroNumber = 0
    static let halfMinute = 30_000

    static let pathDb = "{0}.sqlite"
    static let ok = "OK"
    
    static let new = "NEW"
    static let logout = "logout"
    static let restart = "restart"
    static let initialize = "{INITIALIZE}"
    static let weather_m_d_ww = "{0}月{1}日 {2}"

    // Color Define
    static let colorPrimary = UIColor(rgb: 0x009af3)
    static let colorPrimaryDark = UIColor(rgb: 0x2a24a7)
    static let textColorPrimary = UIColor(rgb: 0xffffff)
    static let colorAccent = UIColor(rgb: 0xffffff)
    static let accentOrange = UIColor(rgb: 0xf79646)
    static let textDark = UIColor(rgb: 0x333333)
    static let textDarkBold = UIColor(rgb: 0x111111)
    static let textSummary = UIColor(rgb: 0x666666)
    static let textHint = UIColor(rgb: 0xaaaaaa)
    static let home_bnv_bg = UIColor(rgb: 0xffe7f4fe)
    static let bell_normal = UIColor(rgb: 0x4B4B4B)
    static let bell_important = UIColor(rgb: 0xEE8833)
    static let gray_out = UIColor(rgb: 0xcccccccc)
    static let orange_out = UIColor(rgb: 0xEEDDBB)
    static let color2 = UIColor(rgb: 0xF5F5F5)
    static let defaultBackground = UIColor(rgb: 0xF5F5F5)
    static let listItem = UIColor(rgb: 0xFFFFFF)
    static let textColor = UIColor(rgb: 0x6d6d6d)
    static let lightText = UIColor(rgb: 0xffffff)
    static let primaryLight = UIColor(rgb: 0x68bded)
    static let grayBackground = UIColor(rgb: 0xE6E6E6)
    
    static let app_name = "Trustar"
    static let trustar = "Trustar"
    static let title_m_d_w = "{0}月{1}日（{2}）"
    static let company_id = "企業ID"
    static let user_id = "ユーザーID"
    static let password = "パスワード"
    static let login = "ログイン"
    static let switch_user = "ユーザー切替"
    static let login_footer_info = "パスワードを忘れた方は、\nサポートに連絡してください。"
    static let login_auth_err = "認証エラー"
    static let login_auth_wrong_msg = "IDまたはパスワードが間違っています。"
    static let login_auth_invalid_account_msg = "アカウントが失効しています。"
    static let login_auth_password_expired_msg = "パスワードの有効期限が切れています。"
    static let s1_field_required = "を入力してください"
    static let terminal_id_s1 = "端末ID："
    static let login_sso_alert_msg = "既にログインされています。現在のログイン情報は破棄されますがよろしいですか？"
    static let login_disabled = "ログイン権限がありません。"
    static let notice_mark_read = "お知らせを確認した"
    static let tf_weather_today = "本日のお天気は？"
    static let goto_home_dashboard = "ダッシュボードへ"
    static let home_navigation_dashboard = "ダッシュボード"
    static let home_navigation_deliver = "配送計画"
    static let home_navigation_operation = "作業入力"
    static let home_navigation_refuel = "給油"
    static let settings = "設定"
    static let ask_for_support = "システムの問い合わせ"
    static let weather_settings = "天気を変更する"
    static let dashboard_normal = "通常"
    static let dashboard_important = "重要"
    static let change_vehicle = "車両変更"
    static let choose_vehicle = "車両選択"
    static let weather_setup_close = "天気を設定する"
    static let weather_hare = "晴れ"
    static let weather_kumori = "曇り"
    static let weather_ame = "雨"
    static let weather_yuki = "雪"
    static let weather_hare_kumori = "晴れ時々曇り"
    static let weather_kumori_hare = "曇り時々晴れ"
    static let weather_need_to_be_set_msg = "天候が未設定です。設定画面から天候を設定してください"
    static let today_operation_amount_d = "本日の運行：{0}件"
    static let today_operation_remain_d = "残り：{0}件"
    static let show_all = "全て表示"
    static let operation_add_unscheduled = "計画なし運行追加"
    static let server_connection_err = "通信エラー"
    static let start_bin_connection_err_alert_msg = "運行開始に失敗しました。電波状況を確認し、オンライン状態で再度実行してください。"
    static let sync_connection_err_alert_msg = "通信に失敗しました。電波状況を確認し、オンライン状態で再度実行してください。"
    static let operation_start = "運行開始"
    static let operation_end = "運行終了"
    static let start_when_started_operation_exists_msg = "他に運行中の配送があるため、運行を開始できません"
    static let end_when_working_exists_msg = "作業途中のため、運行を終了できません"
    static let end_when_ready_exists_alert_title = "確認【未作業あり】"
    static let end_when_ready_exists_alert_msg = "未作業の場所があります。運行を終了してもよろしいですか？"
    static let operation_end_alert_msg = "運行を終了してもよろしいですか？"
    static let work_add = "追加作業"
    static let work_in_advance = "早配"
    static let work_delayed = "遅配"
    static let work_misdelivered = "誤配"
    static let work_notice_of_time = "指定時間厳守でお願いします。"
    static let work_mode_select_title = "作業モードを選択して下さい"
    static let work_mode_select_msg = "※地点情報のない配送先があります。\n自動モードを選択する場合は「地点情報なし」の表示のある配送先の到着時に行を押下して地点情報を登録してください。"

    static let work_mode_automatic = "自動モード"
    static let work_mode_manual = "手動モード"
    static let tip_automatic_title = "自動モードが有効になりました"
    static let tip_automatic_msg = "※作業入力を自身で行う場合は手動モードに切り替えてください"
    static let tip_manual_title = "手動モードが有効になりました"
    static let tip_manual_msg = "※作業入力を自動で行う場合は自動モードに切り替えてください"
    static let tip_checkbox = "次回から表示しない"
    static let work_move_to_destination_title = "選択地に移動しますか？"
    static let work_move_to_destination_msg = "移動するとステータスが\"移動中\"に変更されます。"
    static let work_move = "移動"
    static let cancel = "キャンセル"
    static let clear = "クリア"
    static let confirm = "確認"
    static let determine = "確定"
    static let yes = "はい"
    static let no = "いいえ"
    static let input_later = "後で入力"
    static let work_start_without_dest_location_msg = "地点情報の仮登録を行います。配送先に登録していますか？"
    static let work_misdelivered_alert_title = "警告【誤配】"
    static let work_misdelivered_alert_msg = "現在地は予定された作業地ではない可能性があります。作業を開始しますか？"
    static let work_before_operation_start_tip = "運行を開始してください"
    static let work_after_operation_finished_tip = "既に運行が終了しています"
    static let work_start_by_s1_alert_title = "\"%s\"を開始しますか？"
    static let work_start_alert_msg = "開始すると作業中画面に切り替わります。"
    static let move_work_when_working_exists_msg = "作業途中のため、移動することはできません"
    static let start = "開始"
    static let work_end = "作業終了"
    static let work_status_s1_ing = "%s中"
    static let work_status_s1_end = "%s終了"
    static let refuel_amount_of_the_operation = "この運行での給油量"
    static let refuel_amount_in_liter = "給油量（L）"
    static let amount_include_tax = "金額（税込み支払金額）"
    static let confirm_input = "入力を確定する"
    static let refuel_success_msg = "給油情報を登録しました"
    static let unselected = "未選択"
    static let f_liter = "%.1fL"
    static let current_vehicle = "現在の車両"
    static let vehicle_search_hint = "車両コードまたは車両名を入力"
    static let choose_target_vehicle = "変更後の車両を選択"
    static let vehicle_changed_msg = "車両を変更しました"
    static let operation_start_by_this_vehicle = "この車両で運行を開始しますか？"
    
    static let zipcode = "郵便番号"
    static let zipcode_query = "検索"
    static let delivery_emphasis = "強調切替"

    static let memo = "メモ"
    static let title = "タイトル"

    static let new_create = "新規登録"
    static let delivery_edit = "編集"
    static let delivery_chart = "納品先カルテ"
    static let delivery_dest_info = "納品先情報"
    static let delivery_dest = "納品先"
    static let delivery_dest_addr = "住所"
    static let delivery_dest_addr1 = "住所1"
    static let delivery_dest_addr2 = "住所2"
    static let delivery_dest_tel = "TEL"
    static let delivery_carrier = "担当者"
    static let delivery_carrier_tel = "担当者TEL"
    static let delivery_photo = "写真（入り口、建物など）"
    static let delivery_photo_del_msg = "表示中の画像を削除します。よろしいですか？"
    static let delivery_memo = "メモ、特記事項"

    static let user_cannot_be_selected = "このユーザーは選択できません"
    static let user_cannot_be_deleted = "このユーザーは削除できません"
    static let bin_untimely_delivered_reason = "遅早配理由"
    static let bin_untimely_delivered_reason_change = "理由変更"
    static let bin_service_order = "計画運行順"
    static let bin_operation_order = "実績運行順"
    static let bin_place_name = "発着地"
    static let bin_plan_time = "指定時間"
    static let bin_actual_time = "実績時間"
    static let bin_work_name = "作業名"
    static let bin_zip_code = "郵便番号"
    static let bin_place_address = "住所"
    static let bin_place_tel1 = "Tel"
    static let bin_place_mail1 = "Mail"
    static let bin_place_tel2 = "担当者Tel"
    static let bin_place_mail2 = "担当者Mail"
    static let bin_place_note1 = "備考1"
    static let bin_place_note2 = "備考2"
    static let bin_place_note3 = "備考3"
    static let bin_additional_info = "附帯情報"
    static let bin_incidental = "待機附帯"
    static let bin_signature = "署名"
    static let bin_temperature = "温度"
    static let bin_memo = "メモ"
    static let bin_registered = "登録あり"
    static let empty_placeholder = "データがありません"
    static let permission_request_msg_location = "位置情報の権限を追加してください。"
    static let permission_request_msg_notification = "通知を許可してください。\n【許可しない】を選択した場合は通知が表示されません。"
    static let app_settings_location_background_permission_msg = "位置情報の権限画面で「常に許可する」を選択してください。"
//        static let notification_battery_saver_is_on_title = "バッテリーセーバーを解除してください。"
//        static let notification_battery_saver_is_on_text = "バッテリーセーバーが位置情報の記録を妨げることがあります。"
//        static let notification_battery_saver_is_on_big_text = "OS側のバッテリーセーバーが有効になっています。バッテリーセーバーがアプリケーションの位置情報の記録を妨げることがあります。OS側のバッテリーセーバーを解除してください。"
//
    static let notice_send_data_alert_title = "データ送信"
    static let notice_send_data_alert_msg = "アプリケーションのデータをシステム管理者に送信します。\nよろしいですか？"
//
    static let invalid_account_alert_msg = "ログアウトしました。もう一度ログインしてください。"
//        static let sign_place = "署名欄"
    static let sign_inside_area = "枠内に署名してください"
//        static let shipper = "荷主"
//        static let select_shipper = "荷主選択"
    static let change_shipper = "荷主変更"
    static let current_shipper = "現在の荷主"
    static let shipper_search_hint = "荷主コードまたは荷主名を入力"
    static let choose_target_shipper = "変更後の荷主を選択"
    static let update = "更新"
    static let edit = "編集"
    static let confirm_content = "内容を確定する"
    static let update_content = "内容を更新する"
    static let signed = "署名済み"
    static let unsigned = "未署名"
    static let set_time = "時刻設定"
    static let pick_start_time = "開始時刻"
    static let pick_end_time = "終了時刻"
    static let select_work = "作業を選択"
    static let tap_to_edit = "タップしてください"
    static let incidental_sheets = "待機・附帯登録"
    static let incidental_sheet_works_selection = "実施した作業を選択"
    static let incidental_back_sheet_list = "一覧に戻る"
    static let incidental_sheet_new_create = "新規登録"
    static let incidental_created = "登録済みの荷主"
    static let incidental_sheet_addition_work_ = "附帯作業内容："
    static let incidental_sheet_await = "荷待待機"
    static let incidental_sheet_addition_work = "附帯作業"
    static let incidental_sheet_signature = "荷主担当者様の署名"
    static let unregistered_placeholder = "(未登録)"
    static let invalid_time_range = "開始時刻は終了時刻以前に設定してください。"
//        static let loading_image = "画像の読み込み中"
    static let outgoing_meter_input_title = "出庫メーターを入力してください。"
    static let outgoing_meter_in_km = "出庫メーター(km)"
    static let incoming_meter_input_title = "入庫メーターを入力してください。"
    static let incoming_meter_in_km = "入庫メーター(km)"

    static let bin_vehicle = "車両名"
    static let bin_start_scheduled_time = "運行開始予定日時"
    static let bin_end_scheduled_time = "運行終了予定日時"
    static let bin_start_time = "運行開始日時"
    static let bin_end_time = "運行終了日時"
    static let bin_crew = "乗務員"
    static let bin_crew2 = "副乗務員"
    static let bin_note_1 = "備考1"
    static let bin_outgoing_meter = "出庫メーター"
    static let bin_incoming_meter = "入庫メーター"
    static let data_resend = "再送信"
    static let data_end_data_sending = "運行終了処理中です。"
    static let data_end_data_sending_msg = "運行終了処理中の間はアプリを落とさないで下さい。"

//        static let location_1 = "地点情報あり"
    static let location_0 = "地点情報なし"
    static let collections = "集配物"
    static let collections_edit = "集配物登録"
    static let expected_quantity = "予定数"
    static let actual_quantity = "実績数"
    
    static let room_create_err_alert_msg = "トークルームの作成に失敗しました。システム管理者に連絡してください"
    static let room_add_user_err_alert_msg = "ユーザーの追加に失敗しました。システム管理者に連絡してください"
    static let room_quit_s1_alert_msg = "「%s」から退出しますか？"
    static let room_leave_err_alert_msg = "退出に失敗しました。システム管理者に連絡してください"
    static let room_update_settings_err_alert_msg = "設定の変更に失敗しました。システム管理者に連絡してください"
    static let chat_retry = "ネットワーク接続が不安定です。\nタップしてメッセージを再取得します。"
    static let msg_tap_to_retry = "送信失敗。タップして再送信"
    static let msg_sending = "送信中"
    static let msg_been_read = "既読"
    static let tap_to_download = "タップしてダウンロード"
    static let download = "ダウンロード"
    static let downloaded = "ダウンロードしました"
    static let downloading = "ダウンロード中"
    static let open_with = "アプリケーションを選択"
    static let new_d_messages = "%d件の新着メッセージがあります"
    static let network_error = "ネットワークエラー"
    static let msg_options_copy = "コピー"
    static let msg_options_copied = "コピーしました"
    static let msg_options_details = "詳細を表示"
    static let msg_details = "詳細"
    static let msg_options_sent_time = "送信日時：%s"
    static let app_permission_settings_location = "この機器の位置情報へのアクセスをTrustarに許可してください。"
    static let app_permission_settings_camera = "写真と動画の撮影をTrustarに許可してください。"
    static let app_permission_settings_storage = "端末内の写真、メディア、ファイルへのアクセスをTrustarに許可してください。"
    static let app_permission_settings_image = "端末内の写真へのアクセスをTrustarに許可してください。"
    static let app_permission_settings_audio_record = "録音をTrustarに許可してください。"

    static let search_by_name = "名前で検索"
    static let talk_history = "トーク履歴"
    static let logged_in_user = "登録ユーザー"
    static let talk_option = "Option"
    static let talk_room_settings = "トークルーム設定"
    static let create_talk_room = "トークルームの作成"
    static let allow_notification = "通知を許可する"
    static let quit_talk_room = "トークルームから退出する"
    static let members_of_room_other = "%d 人の参加者"
    static let user_selected_other = "%d 名選択中"
    static let add_user = "ユーザーを追加する"
    static let create_new_item = "新しい項目の登録"
    static let add = "追加"
    static let camera_roll = "カメラロール"
    static let camera_opening = "オープニング"
    static let determine2 = "確定"
    static let item_selected_other = "%d 件選択中"
    static let updating = "更新処理中"
    static let processing = "処理中"
    static let hint_input_text = "内容を入力"
    static let create = "作成"
    static let audio_file = "音声ファイル"
    static let preview = "プレビュー"
    static let share = "共有"
    static let delete = "削除"
    static let alert_delete_message_msg = "このメッセージを削除しますか？"
    static let quit = "退出"
    static let load_failed = "情報の取得に失敗しました。"
    static let talk = "トーク"
    static let navigation_message = "メッセージ"

    static let notification_location_is_off_title = "位置情報の取得がOFFになっています。現在位置を取得するためにONにしてください。"
    
    static let ic_avatar = "ic_avatar"
    static let round_broken_image_24 = "round-broken-image"
    static let round_photo_24 = "round-photo"
    static let x_mark = "xmark"
    static let checkmark = "checkmark"
    
    static let copy_clipboard = "クリップボードにコピーしました。"
    static let update_version_title = "アプリアップデート"
    static let update_version_content = "新しいバージョンのアプリがあります。\nアップデートしてください。"
    static let close = "CLOSE"
}
