//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMacOs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorihikiMvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に失敗しました。.
        /// </summary>
        public static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行しました。.
        /// </summary>
        public static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を成功に実行しました。.
        /// </summary>
        public static string ActionSuccess2 {
            get {
                return ResourceManager.GetString("ActionSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に失敗しました。.
        /// </summary>
        public static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常に連携されました。.
        /// </summary>
        public static string ApiResponseSuccess {
            get {
                return ResourceManager.GetString("ApiResponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azureサーバーに接続できません。更新し直して下さい。.
        /// </summary>
        public static string AzureConnectFailed {
            get {
                return ResourceManager.GetString("AzureConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消しました。.
        /// </summary>
        public static string CancelSuccess {
            get {
                return ResourceManager.GetString("CancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントローラーが設定されません。.
        /// </summary>
        public static string ControllerSettingError {
            get {
                return ResourceManager.GetString("ControllerSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルフォーマットエラー.
        /// </summary>
        public static string CsvFormatError {
            get {
                return ResourceManager.GetString("CsvFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが存在していません。.
        /// </summary>
        public static string DataNotExisted {
            get {
                return ResourceManager.GetString("DataNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが存在していない、または削除しました。ご確認ください。.
        /// </summary>
        public static string DataNotExisted2 {
            get {
                return ResourceManager.GetString("DataNotExisted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}にデータが存在していません。ご確認ください。.
        /// </summary>
        public static string DataNotExisted3 {
            get {
                return ResourceManager.GetString("DataNotExisted3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に日付を入力してください。.
        /// </summary>
        public static string DateTypeError {
            get {
                return ResourceManager.GetString("DateTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメント更新はできません。.
        /// </summary>
        public static string DocumentListNonUpate {
            get {
                return ResourceManager.GetString("DocumentListNonUpate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正しいメールアドレスを入力してください。.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}と{1}の値は同じではありません。.
        /// </summary>
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。ログファイルを参照してください。.
        /// </summary>
        public static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。&lt;br/&gt;{0}.
        /// </summary>
        public static string ExceptionError2 {
            get {
                return ResourceManager.GetString("ExceptionError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行します。よろしいでしょうか。.
        /// </summary>
        public static string ExecuteConfirm {
            get {
                return ResourceManager.GetString("ExecuteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}のフォーマットは不正です。.
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プリンター情報を取得出来ません。&lt;br/&gt;SVF Web Direct Printを起動してください。.
        /// </summary>
        public static string GetPrinterInfoFailed {
            get {
                return ResourceManager.GetString("GetPrinterInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}より大きなのように入力してください。.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象データが多いため検索結果を表示できません。&lt;br /&gt;上限件数：{0}&lt;br /&gt;対象データ件数：{1}.
        /// </summary>
        public static string GreaterTranMaxRowCount {
            get {
                return ResourceManager.GetString("GreaterTranMaxRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辞退しました.
        /// </summary>
        public static string JitaiSuccess {
            get {
                return ResourceManager.GetString("JitaiSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を辞退しました.
        /// </summary>
        public static string JitaiSuccess2 {
            get {
                return ResourceManager.GetString("JitaiSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容確認しました。.
        /// </summary>
        public static string KakuninSuccess {
            get {
                return ResourceManager.GetString("KakuninSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を内容確認しました。.
        /// </summary>
        public static string KakuninSuccess2 {
            get {
                return ResourceManager.GetString("KakuninSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 却下します。よろしいでしょうか。.
        /// </summary>
        public static string KyakkaConfirm {
            get {
                return ResourceManager.GetString("KyakkaConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 却下しました。.
        /// </summary>
        public static string KyakkaSuccess {
            get {
                return ResourceManager.GetString("KyakkaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を却下しました。.
        /// </summary>
        public static string KyakkaSuccess2 {
            get {
                return ResourceManager.GetString("KyakkaSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定します。よろしいですか？.
        /// </summary>
        public static string KYC000001 {
            get {
                return ResourceManager.GetString("KYC000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存します。よろしいですか？.
        /// </summary>
        public static string KYC000002 {
            get {
                return ResourceManager.GetString("KYC000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請します。よろしいですか？.
        /// </summary>
        public static string KYC000003 {
            get {
                return ResourceManager.GetString("KYC000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除します。よろしいですか？.
        /// </summary>
        public static string KYC000004 {
            get {
                return ResourceManager.GetString("KYC000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を確定しました。&lt;br /&gt;続けて{1}を行いますか？.
        /// </summary>
        public static string KYC000005 {
            get {
                return ResourceManager.GetString("KYC000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集中データがあります。&lt;br /&gt;破棄しますか？.
        /// </summary>
        public static string KYC000006 {
            get {
                return ResourceManager.GetString("KYC000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を行います。よろしいですか？.
        /// </summary>
        public static string KYC000007 {
            get {
                return ResourceManager.GetString("KYC000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}をコピーしますか？.
        /// </summary>
        public static string KYC000008 {
            get {
                return ResourceManager.GetString("KYC000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を超えています。よろしいですか？.
        /// </summary>
        public static string KYC000009 {
            get {
                return ResourceManager.GetString("KYC000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に出力しています。再出力しますか？.
        /// </summary>
        public static string KYC000010 {
            get {
                return ResourceManager.GetString("KYC000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消します。よろしいですか？.
        /// </summary>
        public static string KYC000011 {
            get {
                return ResourceManager.GetString("KYC000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解除します。よろしいですか？.
        /// </summary>
        public static string KYC000012 {
            get {
                return ResourceManager.GetString("KYC000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が未登録です。確定してもよろしいですか？.
        /// </summary>
        public static string KYC000013 {
            get {
                return ResourceManager.GetString("KYC000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が未登録です。出力してもよろしいですか？.
        /// </summary>
        public static string KYC000014 {
            get {
                return ResourceManager.GetString("KYC000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が含まれています。削除してもよろしいですか？.
        /// </summary>
        public static string KYC000015 {
            get {
                return ResourceManager.GetString("KYC000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が含まれています。出力してもよろしいですか？.
        /// </summary>
        public static string KYC000016 {
            get {
                return ResourceManager.GetString("KYC000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集中データがあります。確定してもよろしいですか？.
        /// </summary>
        public static string KYC000017 {
            get {
                return ResourceManager.GetString("KYC000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を確定しました。&lt;br /&gt;{1}&lt;br /&gt;続けて{2}を行いますか？.
        /// </summary>
        public static string KYC000018 {
            get {
                return ResourceManager.GetString("KYC000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を入力してください。.
        /// </summary>
        public static string KYE000001 {
            get {
                return ResourceManager.GetString("KYE000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を選択してください。.
        /// </summary>
        public static string KYE000002 {
            get {
                return ResourceManager.GetString("KYE000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を指定してください。.
        /// </summary>
        public static string KYE000003 {
            get {
                return ResourceManager.GetString("KYE000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以内で入力してください。.
        /// </summary>
        public static string KYE000004 {
            get {
                return ResourceManager.GetString("KYE000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}から{2}の間で入力してください。.
        /// </summary>
        public static string KYE000005 {
            get {
                return ResourceManager.GetString("KYE000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以上を入力してください。.
        /// </summary>
        public static string KYE000006 {
            get {
                return ResourceManager.GetString("KYE000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以降の日付で入力してください。.
        /// </summary>
        public static string KYE000007 {
            get {
                return ResourceManager.GetString("KYE000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以前の日付で入力してください。.
        /// </summary>
        public static string KYE000008 {
            get {
                return ResourceManager.GetString("KYE000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}より未来の日付で入力してください。.
        /// </summary>
        public static string KYE000009 {
            get {
                return ResourceManager.GetString("KYE000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}より過去の日付で入力してください。.
        /// </summary>
        public static string KYE000010 {
            get {
                return ResourceManager.GetString("KYE000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}の場合、{2}を入力してください。.
        /// </summary>
        public static string KYE000011 {
            get {
                return ResourceManager.GetString("KYE000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を選択もしくは入力してください。.
        /// </summary>
        public static string KYE000012 {
            get {
                return ResourceManager.GetString("KYE000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}削除できません。.
        /// </summary>
        public static string KYE000013 {
            get {
                return ResourceManager.GetString("KYE000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象データは１件のみ選択してください。.
        /// </summary>
        public static string KYE000014 {
            get {
                return ResourceManager.GetString("KYE000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は登録できません。.
        /// </summary>
        public static string KYE000015 {
            get {
                return ResourceManager.GetString("KYE000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、登録できません。.
        /// </summary>
        public static string KYE000016 {
            get {
                return ResourceManager.GetString("KYE000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が異なる明細は同時に登録できません。.
        /// </summary>
        public static string KYE000017 {
            get {
                return ResourceManager.GetString("KYE000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}がすでに登録済みです。.
        /// </summary>
        public static string KYE000018 {
            get {
                return ResourceManager.GetString("KYE000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}と{1}は同時に設定できません。.
        /// </summary>
        public static string KYE000019 {
            get {
                return ResourceManager.GetString("KYE000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}選択することはできません。.
        /// </summary>
        public static string KYE000020 {
            get {
                return ResourceManager.GetString("KYE000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伝票Noを跨いで選択することはできません。.
        /// </summary>
        public static string KYE000021 {
            get {
                return ResourceManager.GetString("KYE000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は変更できません。.
        /// </summary>
        public static string KYE000022 {
            get {
                return ResourceManager.GetString("KYE000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}と一致していません。.
        /// </summary>
        public static string KYE000023 {
            get {
                return ResourceManager.GetString("KYE000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を超える{1}は入力できません。.
        /// </summary>
        public static string KYE000024 {
            get {
                return ResourceManager.GetString("KYE000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に{1}を設定できません。.
        /// </summary>
        public static string KYE000025 {
            get {
                return ResourceManager.GetString("KYE000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は参照できません。.
        /// </summary>
        public static string KYE000026 {
            get {
                return ResourceManager.GetString("KYE000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、参照できません。.
        /// </summary>
        public static string KYE000027 {
            get {
                return ResourceManager.GetString("KYE000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は出力できません。.
        /// </summary>
        public static string KYE000028 {
            get {
                return ResourceManager.GetString("KYE000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、出力できません。.
        /// </summary>
        public static string KYE000029 {
            get {
                return ResourceManager.GetString("KYE000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力対象外です。.
        /// </summary>
        public static string KYE000030 {
            get {
                return ResourceManager.GetString("KYE000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、{1}できません。{2}を行ってください。.
        /// </summary>
        public static string KYE000031 {
            get {
                return ResourceManager.GetString("KYE000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以上を入力してください。{2}.
        /// </summary>
        public static string KYE000032 {
            get {
                return ResourceManager.GetString("KYE000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以下を入力してください。{2}.
        /// </summary>
        public static string KYE000033 {
            get {
                return ResourceManager.GetString("KYE000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は存在しません。.
        /// </summary>
        public static string KYE000034 {
            get {
                return ResourceManager.GetString("KYE000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、削除できません。.
        /// </summary>
        public static string KYE000035 {
            get {
                return ResourceManager.GetString("KYE000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の場合のみ、{1}ができます。.
        /// </summary>
        public static string KYE000036 {
            get {
                return ResourceManager.GetString("KYE000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}登録してください。.
        /// </summary>
        public static string KYE000037 {
            get {
                return ResourceManager.GetString("KYE000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}承認できません。.
        /// </summary>
        public static string KYE000038 {
            get {
                return ResourceManager.GetString("KYE000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}がありません。.
        /// </summary>
        public static string KYE000039 {
            get {
                return ResourceManager.GetString("KYE000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}取消できません。.
        /// </summary>
        public static string KYE000040 {
            get {
                return ResourceManager.GetString("KYE000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以降の時間で入力してください。.
        /// </summary>
        public static string KYE000041 {
            get {
                return ResourceManager.GetString("KYE000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以前の時間で入力してください。.
        /// </summary>
        public static string KYE000042 {
            get {
                return ResourceManager.GetString("KYE000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、解除できません。.
        /// </summary>
        public static string KYE000043 {
            get {
                return ResourceManager.GetString("KYE000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の為、{1}できません。{2}.
        /// </summary>
        public static string KYE000045 {
            get {
                return ResourceManager.GetString("KYE000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}で入力してください。.
        /// </summary>
        public static string KYE000046 {
            get {
                return ResourceManager.GetString("KYE000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新処理に失敗しました。.
        /// </summary>
        public static string KYE000047 {
            get {
                return ResourceManager.GetString("KYE000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}正しくありません。.
        /// </summary>
        public static string KYE000048 {
            get {
                return ResourceManager.GetString("KYE000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードをルールに従って入力してください。&lt;br /&gt;　１、6文字以上英数字混在。&lt;br /&gt;　２、同じ文字は3文字以上使用不可。.
        /// </summary>
        public static string KYE000049 {
            get {
                return ResourceManager.GetString("KYE000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}してください。.
        /// </summary>
        public static string KYE000050 {
            get {
                return ResourceManager.GetString("KYE000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}できません。.
        /// </summary>
        public static string KYE000051 {
            get {
                return ResourceManager.GetString("KYE000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}為、出力できません。.
        /// </summary>
        public static string KYE000052 {
            get {
                return ResourceManager.GetString("KYE000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}為、登録できません。.
        /// </summary>
        public static string KYE000053 {
            get {
                return ResourceManager.GetString("KYE000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以降の日付で入力してください。{2}.
        /// </summary>
        public static string KYE000054 {
            get {
                return ResourceManager.GetString("KYE000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以前の日付で入力してください。{2}.
        /// </summary>
        public static string KYE000055 {
            get {
                return ResourceManager.GetString("KYE000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}より未来の日付で入力してください。{2}.
        /// </summary>
        public static string KYE000056 {
            get {
                return ResourceManager.GetString("KYE000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}より過去の日付で入力してください。{2}.
        /// </summary>
        public static string KYE000057 {
            get {
                return ResourceManager.GetString("KYE000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他の端末にて更新済みのため、更新できません。.
        /// </summary>
        public static string KYE000058 {
            get {
                return ResourceManager.GetString("KYE000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プリンター情報を取得出来ません。{0}プリンターを設定してください。.
        /// </summary>
        public static string KYE000059 {
            get {
                return ResourceManager.GetString("KYE000059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択しているプリンターがプリンターマスタに登録されていません。.
        /// </summary>
        public static string KYE000060 {
            get {
                return ResourceManager.GetString("KYE000060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notesとの連携に失敗しました。&lt;br /&gt;Notesエラーメッセージ：{0}.
        /// </summary>
        public static string KYE000061 {
            get {
                return ResourceManager.GetString("KYE000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を確定しました。.
        /// </summary>
        public static string KYI000001 {
            get {
                return ResourceManager.GetString("KYI000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を保存しました。.
        /// </summary>
        public static string KYI000002 {
            get {
                return ResourceManager.GetString("KYI000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を申請しました。.
        /// </summary>
        public static string KYI000003 {
            get {
                return ResourceManager.GetString("KYI000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を削除しました。.
        /// </summary>
        public static string KYI000004 {
            get {
                return ResourceManager.GetString("KYI000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が完了しました。.
        /// </summary>
        public static string KYI000005 {
            get {
                return ResourceManager.GetString("KYI000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を取消しました。.
        /// </summary>
        public static string KYI000006 {
            get {
                return ResourceManager.GetString("KYI000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を解除しました。.
        /// </summary>
        public static string KYI000007 {
            get {
                return ResourceManager.GetString("KYI000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を即承認しました。.
        /// </summary>
        public static string KYI000008 {
            get {
                return ResourceManager.GetString("KYI000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を取込ました。.
        /// </summary>
        public static string KYI000009 {
            get {
                return ResourceManager.GetString("KYI000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を確定しました。&lt;br /&gt;{1}.
        /// </summary>
        public static string KYI000010 {
            get {
                return ResourceManager.GetString("KYI000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}設定してください。.
        /// </summary>
        public static string KYW000001 {
            get {
                return ResourceManager.GetString("KYW000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}変更してください。.
        /// </summary>
        public static string KYW000002 {
            get {
                return ResourceManager.GetString("KYW000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に{1}桁を入力してください。.
        /// </summary>
        public static string LengthCheck {
            get {
                return ResourceManager.GetString("LengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}より小さなのように入力してください。.
        /// </summary>
        public static string LessTran {
            get {
                return ResourceManager.GetString("LessTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明細データを選択してください。.
        /// </summary>
        public static string ListDetailsSelectedRequired {
            get {
                return ResourceManager.GetString("ListDetailsSelectedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}存在チェック。{1}.
        /// </summary>
        public static string LogExistedCheck {
            get {
                return ResourceManager.GetString("LogExistedCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}存在チェックは失敗しました。{1}.
        /// </summary>
        public static string LogExistedCheckFailed {
            get {
                return ResourceManager.GetString("LogExistedCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他の端末でログインしました。\nログインするときに、他の端末をサインアウトされます。\nログインしましょうか？.
        /// </summary>
        public static string Logined {
            get {
                return ResourceManager.GetString("Logined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この端末にユーザーはすでにログインしました。.
        /// </summary>
        public static string LoginedWithSameIP {
            get {
                return ResourceManager.GetString("LoginedWithSameIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウトします。よろしいでしょうか？.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は成功しました。{1}.
        /// </summary>
        public static string LogSuccess {
            get {
                return ResourceManager.GetString("LogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以上で入力してください。.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行を追加しました。.
        /// </summary>
        public static string MultiAddSuccess {
            get {
                return ResourceManager.GetString("MultiAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン必要。.
        /// </summary>
        public static string NeedLogin {
            get {
                return ResourceManager.GetString("NeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限なし。.
        /// </summary>
        public static string NoKengen {
            get {
                return ResourceManager.GetString("NoKengen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ件数が多いですので、検索条件を設定してください。.
        /// </summary>
        public static string NoSearchConditionSetted {
            get {
                return ResourceManager.GetString("NoSearchConditionSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当するレコードが見つかりません。.
        /// </summary>
        public static string NoSearchRecord {
            get {
                return ResourceManager.GetString("NoSearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以外を入力してください。.
        /// </summary>
        public static string NotAllow {
            get {
                return ResourceManager.GetString("NotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}と一致ことはできません。.
        /// </summary>
        public static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notesサーバに正常接続できません。.
        /// </summary>
        public static string NotesServerConnectFailure {
            get {
                return ResourceManager.GetString("NotesServerConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}には数字を入力してください.
        /// </summary>
        public static string NumberError {
            get {
                return ResourceManager.GetString("NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を正しく入力してください。.
        /// </summary>
        public static string NYE000001 {
            get {
                return ResourceManager.GetString("NYE000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画面の引数にエラーがあります。ご確認ください。.
        /// </summary>
        public static string PageSessionError {
            get {
                return ResourceManager.GetString("PageSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが変更されました。.
        /// </summary>
        public static string PasswordBeenChanged {
            get {
                return ResourceManager.GetString("PasswordBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}文字.
        /// </summary>
        public static string PlaceHolderMaxLength {
            get {
                return ResourceManager.GetString("PlaceHolderMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は正規表現 &quot;{1}&quot; と一致する必要があります。.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバに正常接続できません。.
        /// </summary>
        public static string ResponseErrorStatus0 {
            get {
                return ResourceManager.GetString("ResponseErrorStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お探しのページは見つかりませんでした。.
        /// </summary>
        public static string ResponseErrorStatus404 {
            get {
                return ResourceManager.GetString("ResponseErrorStatus404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行を追加しました。.
        /// </summary>
        public static string RowsAddSuccess {
            get {
                return ResourceManager.GetString("RowsAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行をコピーしました。.
        /// </summary>
        public static string RowsCopySuccess {
            get {
                return ResourceManager.GetString("RowsCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行を挿入しました。.
        /// </summary>
        public static string RowsInsertSuccess {
            get {
                return ResourceManager.GetString("RowsInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行を下に移動しました。.
        /// </summary>
        public static string RowsMoveDownSuccess {
            get {
                return ResourceManager.GetString("RowsMoveDownSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行を上に移動しました。.
        /// </summary>
        public static string RowsMoveUpSuccess {
            get {
                return ResourceManager.GetString("RowsMoveUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他の端末にログインしたので、この端末で開いている画面はすべて閉じられます。.
        /// </summary>
        public static string SameUserLogined {
            get {
                return ResourceManager.GetString("SameUserLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッションタイムアウトしました。.
        /// </summary>
        public static string SessionTimeOutError {
            get {
                return ResourceManager.GetString("SessionTimeOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッションタイムアウトしました。再度ログインしてください。.
        /// </summary>
        public static string SessionTimeOutLogin {
            get {
                return ResourceManager.GetString("SessionTimeOutLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認します。よろしいでしょうか。.
        /// </summary>
        public static string ShouninConfirm {
            get {
                return ResourceManager.GetString("ShouninConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認しました。.
        /// </summary>
        public static string ShouninSuccess {
            get {
                return ResourceManager.GetString("ShouninSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を承認しました。.
        /// </summary>
        public static string ShouninSuccess2 {
            get {
                return ResourceManager.GetString("ShouninSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は不正です。.
        /// </summary>
        public static string TelPhoneError {
            get {
                return ResourceManager.GetString("TelPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードできるファイル数の上限({0})を超えています。.
        /// </summary>
        public static string UploadFilesMaxCount {
            get {
                return ResourceManager.GetString("UploadFilesMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたファイルタイプは不正です。.
        /// </summary>
        public static string UploadFileTypeLimit {
            get {
                return ResourceManager.GetString("UploadFileTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に日付を入力してください。.
        /// </summary>
        public static string WarekiDateError {
            get {
                return ResourceManager.GetString("WarekiDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は不正です。.
        /// </summary>
        public static string ZipCodeError {
            get {
                return ResourceManager.GetString("ZipCodeError", resourceCulture);
            }
        }
    }
}
